"""add_address_management_fields

Revision ID: 6c2d3dab96c0
Revises: a78dfd3f18b7
Create Date: 2026-08-01 17:14:58.232476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c2d3dab96c0'
down_revision: Union[str, Sequence[str], None] = 'a78dfd3f18b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new values to existing PostgreSQL addresstype enum
    op.execute("ALTER TYPE addresstype ADD VALUE IF NOT EXISTS 'Home'")
    op.execute("ALTER TYPE addresstype ADD VALUE IF NOT EXISTS 'Office'")
    op.execute("ALTER TYPE addresstype ADD VALUE IF NOT EXISTS 'Other'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('full_name', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('phone', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('address_line_1', sa.String(), nullable=False))
    op.add_column('addresses', sa.Column('address_line_2', sa.String(), nullable=True))
    op.add_column('addresses', sa.Column('is_default_shipping', sa.Boolean(), nullable=False))
    op.add_column('addresses', sa.Column('is_default_billing', sa.Boolean(), nullable=False))
    op.add_column('addresses', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('addresses', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.drop_column('addresses', 'street_address')
    op.drop_column('addresses', 'phone_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('addresses', sa.Column('street_address', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('addresses', 'updated_at')
    op.drop_column('addresses', 'created_at')
    op.drop_column('addresses', 'is_default_billing')
    op.drop_column('addresses', 'is_default_shipping')
    op.drop_column('addresses', 'address_line_2')
    op.drop_column('addresses', 'address_line_1')
    op.drop_column('addresses', 'phone')
    op.drop_column('addresses', 'full_name')
    # ### end Alembic commands ###
